### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by som028** [carlomazzaferro/scikit-hts#43]
* scikit-hts version: 0.5.3
* Python version: python 3.7
* Operating System: MacOS

### Description

Trying to recreate example  available on scikit-hts-examples/notebooks/ using below data

from hts.utilities.load_data import load_hierarchical_sine_data

sine_hier = {'total': ['a', 'b', 'c'], 'a': ['aa', 'ab'], 'aa': ['aaa', 'aab'], 'b': ['ba', 'bb'], 'c': ['ca', 'cb', 'cc', 'cd']}
s, e = datetime(2019, 1, 15), datetime(2019, 10, 15)
df = load_hierarchical_sine_data(s, e).resample('1H').apply(sum)

### What I Did
Works
reg = HTSRegressor(model='sarimax', revision_method='OLS')
reg = reg.fit(df=df, nodes=sine_hier)

Does not work
preds = reg.predict(steps_ahead=10)

I also tried different models but none works.

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/anaconda3/lib/python3.7/site-packages/hts/utilities/distribution.py", line 40, in _function_with_partly_reduce
    return list(results)
  File "/home/user/anaconda3/lib/python3.7/site-packages/hts/utilities/distribution.py", line 39, in <genexpr>
    results = (map_function(chunk, kwargs) for chunk in chunk_list)
  File "/home/user/anaconda3/lib/python3.7/site-packages/hts/core/utils.py", line 99, in _do_actual_predict
    **function_kwargs['predict_kwargs'])
  File "/home/user/anaconda3/lib/python3.7/site-packages/hts/model/ar.py", line 108, in predict
    return self._set_results_return_self(in_sample_preds, y_hat)
  File "/home/user/anaconda3/lib/python3.7/site-packages/hts/model/base.py", line 69, in _set_results_return_self
    self.residual = (in_sample - self.node.get_series()).values
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 503, in wrapper
    right = to_series(right)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 197, in arithmetic_op
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 149, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 228, in evaluate
    use_numexpr = use_numexpr and _bool_arith_check(op_str, a, b)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by carlomazzaferro** [comment]
I can't reproduce on master, what is your `pip freeze` output? 

Feel free to compare to mine, which I just ran from fresh on `scikit-hts-examples` after issuing `make install-all` 

![Screenshot 2020-11-01 at 14 15 00](https://user-images.githubusercontent.com/9201443/97803912-a407d100-1c4c-11eb-9f0b-a0dd55e6fabc.png)


```
!pip freeze
appdirs==1.4.4
appnope==0.1.0
atomicwrites==1.3.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
branca==0.3.1
bumpversion==0.5.3
certifi==2019.11.28
chardet==3.0.4
circ==0.1.0
Click==7.0
cloudpickle==1.6.0
cmdstanpy==0.4.0
convertdate==2.2.0
coverage==4.5.4
cycler==0.10.0
Cython==0.29.14
dask==2.30.0
decorator==4.4.1
defusedxml==0.6.0
distlib==0.3.1
distributed==2.13.0
docutils==0.16
entrypoints==0.3
ephem==3.7.7.1
fbprophet==0.6
filelock==3.0.12
folium==0.10.0
h3==3.4.3
HeapDict==1.0.1
holidays==0.9.12
idna==2.8
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
json5==0.8.5
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
keyring==21.1.0
kiwisolver==1.1.0
LunarCalendar==0.0.9
lunardate==0.2.0
MarkupSafe==1.1.1
matplotlib==3.1.3
mistune==0.8.4
more-itertools==7.2.0
msgpack==1.0.0
nbconvert==5.6.1
nbformat==4.4.0
networkx==2.4
notebook==6.0.2
numpy==1.18.1
packaging==19.2
pandas==1.0.1
pandocfilters==1.4.2
parso==0.5.1
pathlib==1.0.1
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
pkginfo==1.5.0.1
plotly==4.6.0
pluggy==0.13.1
pmdarima==1.5.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
psutil==5.7.3
ptyprocess==0.6.0
py==1.8.0
Pygments==2.4.2
PyMeeus==0.3.6
pyparsing==2.4.5
pyrsistent==0.15.5
pystan==2.19.1.1
pytest==5.2.0
pytest-cov==2.5.0
pytest-mock==1.10.0
pytest-runner==4.2
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3.1
pyzmq==18.1.1
readme-renderer==24.0
requests==2.22.0
requests-toolbelt==0.9.1
retrying==1.3.3
scikit-hts==0.5.0
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.9.0
Send2Trash==1.5.0
setuptools-git==1.2
six==1.15.0
sortedcontainers==2.2.2
statsmodels==0.10.2
tblib==1.7.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.1
toolz==0.11.1
tornado==6.0.3
tox==3.19.0
tox-travis==0.12
tqdm==4.43.0
traitlets==4.3.3
twine==3.1.1
typing-extensions==3.7.4.1
urllib3==1.25.7
virtualenv==20.0.30
wcwidth==0.1.7
webencodings==0.5.1
yellowbrick==1.1
zict==2.0.0
zipp==0.6.0
```
