### ISSUE TITLE
[DOCS] Documentation

### ISSUE THREAD

**Issue by juan-carvajal** [carlomazzaferro/scikit-hts#64]
Hi, I was trying out the package but found problems even with the basic examples, The documentation describes the following code:

```
from datetime import datetime
from hts import HTSRegressor
from hts.utilities.load_data import load_hierarchical_sine_data

# load some data
s, e = datetime(2019, 1, 15), datetime(2019, 10, 15)
df = load_hierarchical_sine_data(s, e).resample('1H').apply(sum)
df.head()

reg = HTSRegressor(model='prophet', revision_method='OLS')
reg = reg.fit(df=hsd, nodes=sine_hier)
preds = ht.predict(steps_ahead=10)
```

This code won´t even run, variable names passed to the fit call aren´t even defined.

I think a correct version would be:

```
from datetime import datetime
from hts import HTSRegressor
from hts.utilities.load_data import load_hierarchical_sine_data
import hts

# load some data

if __name__ == "__main__":
    s, e = datetime(2019, 1, 15), datetime(2019, 10, 15)
    hsd = load_hierarchical_sine_data(start=s, end=e, n=10000)
    hier = {'total': ['a', 'b', 'c'],
                'a': ['a_x', 'a_y'],
                'b': ['b_x', 'b_y'],
                'c': ['c_x', 'c_y'],
                'a_x': ['a_x_1', 'a_x_2'],
                'a_y': ['a_y_1', 'a_y_2'],
                'b_x': ['b_x_1', 'b_x_2'],
                'b_y': ['b_y_1', 'b_y_2'],
                'c_x': ['c_x_1', 'c_x_2'],
                'c_y': ['c_y_1', 'c_y_2']
            }

    reg = HTSRegressor(model='prophet', revision_method='OLS')
    reg = reg.fit(df=hsd, nodes=hier)
    preds = reg.predict(steps_ahead=10)
```

Even so, this code fails when making predictions as shown here:
```
Traceback (most recent call last):
  File "d:/Users/jdcarvajal/Desktop/timeseers test/test_hts.py", line 25, in <module>
    preds = reg.predict(steps_ahead=10)
  File "D:\Users\jdcarvajal\Anaconda3\lib\site-packages\hts\core\regressor.py", line 311, in predict
    return self._revise(steps_ahead=steps_ahead)
  File "D:\Users\jdcarvajal\Anaconda3\lib\site-packages\hts\core\regressor.py", line 322, in _revise
    revised_index = self._get_predict_index(steps_ahead=steps_ahead)
  File "D:\Users\jdcarvajal\Anaconda3\lib\site-packages\hts\core\regressor.py", line 328, in _get_predict_index
    start = self.nodes.item.index[-1] + freq
TypeError: unsupported operand type(s) for +: 'Timestamp' and 'NoneType'
```

I think the basic example shown in the documentation should be able to run smoothly. I apologize if this error is caused by an error in the installation, but for the looks of it, I think that is not the case.

**Comment by carlomazzaferro** [comment]
Thanks for raising it. Data needs resampling, just pushed a quick fix to the docs. 

See updated documentation: https://scikit-hts.readthedocs.io/en/latest/usage.html
