### ISSUE TITLE
Pkl file not found error when running fbprophet

### ISSUE THREAD

**Issue by Rajan316** [carlomazzaferro/scikit-hts#88]
* scikit-hts version:0.5.11
* Python version:3.7
* Operating System:Windows

### Description

I am trying to run an fbprophet model on hierarchical time series data. It was working fine till now. All of a sudden it is showing pickle file not found for a particular category

### What I Did
kwargs = {'yearly_seasonality':True,'weekly_seasonality':True,'changepoint_prior_scale':0.5}
clf = HTSRegressor(model='prophet', revision_method='WLSS', n_jobs=4,**kwargs,low_memory=True)
model = clf.fit(warranty_hierarchy_bottom_level, hierarchy)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\rahul\anaconda3\envs\py37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\rahul\anaconda3\envs\py37\lib\site-packages\hts\utilities\distribution.py", line 41, in _function_with_partly_reduce
    return list(results)
  File "C:\Users\rahul\anaconda3\envs\py37\lib\site-packages\hts\utilities\distribution.py", line 40, in <genexpr>
    results = (map_function(chunk, kwargs) for chunk in chunk_list)
  File "C:\Users\rahul\anaconda3\envs\py37\lib\site-packages\hts\core\utils.py", line 57, in _do_actual_fit
    return _fit_serialize_model(instantiated_model, function_kwargs)
  File "C:\Users\rahul\anaconda3\envs\py37\lib\site-packages\hts\core\utils.py", line 66, in _fit_serialize_model
    with open(path, "wb") as p:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rahul\\AppData\\Local\\Temp\\hts_e76ei9g8\\region_1_K360   _A/C & HEATING (001).pkl'
"""

**Comment by skwolvie** [comment]
I have the same error. Any solutions?
